using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MRIV.Migrations
{
    /// <inheritdoc />
    public partial class AddWorkflowConfig : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<bool>(
                name: "SaveToInventory",
                table: "RequisitionItems",
                type: "bit",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<bool>(
                name: "IsAutoGenerated",
                table: "Approvals",
                type: "bit",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<int>(
                name: "StepConfigId",
                table: "Approvals",
                type: "int",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "WorkflowConfigId",
                table: "Approvals",
                type: "int",
                nullable: true);

            migrationBuilder.CreateTable(
                name: "WorkflowConfigs",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    IssueStationCategory = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    DeliveryStationCategory = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_WorkflowConfigs", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "WorkflowStepConfigs",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    WorkflowConfigId = table.Column<int>(type: "int", nullable: false),
                    StepOrder = table.Column<int>(type: "int", nullable: false),
                    StepName = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: false),
                    ApproverRole = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    RoleParameters = table.Column<string>(type: "NVARCHAR(MAX)", nullable: false),
                    Conditions = table.Column<string>(type: "NVARCHAR(MAX)", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_WorkflowStepConfigs", x => x.Id);
                    table.ForeignKey(
                        name: "FK_WorkflowStepConfigs_WorkflowConfigs_WorkflowConfigId",
                        column: x => x.WorkflowConfigId,
                        principalTable: "WorkflowConfigs",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_Approvals_StepConfigId",
                table: "Approvals",
                column: "StepConfigId");

            migrationBuilder.CreateIndex(
                name: "IX_Approvals_WorkflowConfigId",
                table: "Approvals",
                column: "WorkflowConfigId");

            migrationBuilder.CreateIndex(
                name: "IX_WorkflowStepConfigs_WorkflowConfigId",
                table: "WorkflowStepConfigs",
                column: "WorkflowConfigId");

            migrationBuilder.AddForeignKey(
                name: "FK_Approvals_WorkflowConfigs_WorkflowConfigId",
                table: "Approvals",
                column: "WorkflowConfigId",
                principalTable: "WorkflowConfigs",
                principalColumn: "Id");

            migrationBuilder.AddForeignKey(
                name: "FK_Approvals_WorkflowStepConfigs_StepConfigId",
                table: "Approvals",
                column: "StepConfigId",
                principalTable: "WorkflowStepConfigs",
                principalColumn: "Id");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Approvals_WorkflowConfigs_WorkflowConfigId",
                table: "Approvals");

            migrationBuilder.DropForeignKey(
                name: "FK_Approvals_WorkflowStepConfigs_StepConfigId",
                table: "Approvals");

            migrationBuilder.DropTable(
                name: "WorkflowStepConfigs");

            migrationBuilder.DropTable(
                name: "WorkflowConfigs");

            migrationBuilder.DropIndex(
                name: "IX_Approvals_StepConfigId",
                table: "Approvals");

            migrationBuilder.DropIndex(
                name: "IX_Approvals_WorkflowConfigId",
                table: "Approvals");

            migrationBuilder.DropColumn(
                name: "SaveToInventory",
                table: "RequisitionItems");

            migrationBuilder.DropColumn(
                name: "IsAutoGenerated",
                table: "Approvals");

            migrationBuilder.DropColumn(
                name: "StepConfigId",
                table: "Approvals");

            migrationBuilder.DropColumn(
                name: "WorkflowConfigId",
                table: "Approvals");
        }
    }
}
