using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using MRIV.Enums;

namespace MRIV.Models
{
    public class Approval
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public int RequisitionId { get; set; }

        public int? WorkflowConfigId { get; set; }

        public int? StepConfigId { get; set; }

        public int StationId { get; set; }

        public int DepartmentId { get; set; }

        public int StepNumber { get; set; }

        [Required]
        [StringLength(50)]
        public string ApprovalStep { get; set; }

        [Required]
        [StringLength(50)]
        public string? ApprovalAction{ get; set; }

        [Required]
        public string PayrollNo { get; set; }

        [Required]
        public ApprovalStatus ApprovalStatus { get; set; }

        // Who approved this step
        [StringLength(20)]
        public string? ApprovedBy { get; set; }

        [StringLength(500)]
        public string? Comments { get; set; }

        public bool IsAutoGenerated { get; set; }

        [Required]
        public DateTime CreatedAt { get; set; }

        public DateTime? UpdatedAt { get; set; }

        // Add navigation property to Department
        [ForeignKey("DepartmentId")]
        public virtual Department? Department { get; set; }

        // Navigation property
        // Explicitly map the foreign key for Requisition
        [ForeignKey("RequisitionId")]
        public virtual Requisition? Requisition { get; set; }

        [ForeignKey(nameof(WorkflowConfigId))]
        public WorkflowConfig? WorkflowConfig { get; set; }

        [ForeignKey(nameof(StepConfigId))]
        public WorkflowStepConfig? StepConfig { get; set; }
    }
}
